GET http://localhost:8080/employees/listAll
Content-Type: application/json

###

GET http://localhost:8080/employees/4
Content-Type: application/json

###

POST http://localhost:8080/employees/addEmployee
Content-Type: application/json

{
  "id": 2,
  "firstName": "nagender",
  "lastName": "ettikala",
  "email": "nagender@luv2code.com"
}

###


POST http://localhost:8080/employees/update
Content-Type: application/json

{
  "id": 2,
  "firstName": "nagenderr",
  "lastName": "ettikala",
  "email": "nagender22@luv2code.com"
}

###